apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vaultwarden
  namespace: default
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - vaultwarden.example.tld
    secretName: vaultwarden-tls
  rules:
  - host: vaultwarden.example.tld
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vwapp-service
            port:
              number: 80
