apiVersion: v1
kind: Service
metadata:
  name: vwapp-service
  labels:
    app: vwapp
spec:
  type: ClusterIP
  selector:
    app: vwapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80