name: Validate Kubernetes manifests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  kubeconform:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Kubeconform
      uses: bmuschko/setup-kubeconform@v1
    
    - name: Validate manifests
      run: kubeconform -summary -verbose ./k8s
  
  kube-score:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Kubescore
      uses: tobbbles/setup-kubescore@v1.0.3
    - name: kube-score check
      run: kube-score score ./k8s/*.yaml
