name: Validate Kubernetes manifests
on: [push, pull_request]
jobs:
  kubeconform:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        files: ../k8s

    - name: Set up Kubeconform
      uses: bmuschko/setup-kubeconform@v1
    
    - name: Validate manifests
      run: kubeconform -summary -verbose .
      
